# Generated by Django 3.2.4 on 2021-07-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('DS', 'Dishwasher Safe'), ('HW', 'Hand Wash Only'), ('MS', 'Microwave Safe'), ('GH', 'Gets Hot in Microwave'), ('FR', 'Fragile'), ('MU', 'Metal'), ('MP', 'Multiple Pieces'), ('HL', 'Has Lid')], max_length=2)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='use',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='use',
            name='date',
            field=models.DateField(verbose_name='use date'),
        ),
        migrations.AddField(
            model_name='mug',
            name='instructions',
            field=models.ManyToManyField(to='main_app.Instruction'),
        ),
    ]
