# Generated by Django 3.2.4 on 2021-07-10 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210708_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('mug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mug')),
            ],
        ),
    ]
